---
plugins:
  - jest
  - babel

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'prettier'
  - 'plugin:react/recommended'

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

rules:
  import/no-unresolved: true
  import/extensions: true
  react/prop-types: true
